name: Genera e pubblica RSS

on:
  schedule:
    - cron: '*/30 * * * *'  # ogni 30 minuti
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa dipendenze
        run: |
          pip install -r requirements.txt

      - name: Genera circolari.xml
        run: |
          python FeedRSS.py

      - name: Prepara i file per Pages
        run: |
          mkdir pubblica
          mv circolari.xml pubblica/

      - name: Carica i file da pubblicare
        uses: actions/upload-pages-artifact@v1
        with:
          path: pubblica/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Distribuisci su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1