name: Genera RSS

on:
  schedule:
    - cron: '0 7 * * *'  # ogni giorno alle 7:00 UTC (9:00 italiane)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui FeedRSS.py
        run: |
          python FeedRSS.py

      - name: Commit & push circolari.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add circolari.xml
          git commit -m "Aggiorna circolari.xml" || echo "Nessuna modifica"
          git push